name: Build and Push Docker Image

     on:
       push:
         branches: [ main ]
       pull_request:
         branches: [ main ]

     jobs:
       build:
         runs-on: ubuntu-latest
         steps:
         - uses: actions/checkout@v4
         - name: Build Docker image
           run: docker build -t blackswan-app:latest .
         - name: Test Docker image
           run: docker run -d -p 8501:8501 blackswan-app:latest
           # Note: This is a local test; adjust if needed for CI
